version: "3.8"

services:
  backend:
    build:
      context: ./citycounter-backend
    ports:
      - "8080:8080"
    container_name: citycounter-ui

  frontend:
    build:
      context: ./citycounter-ui
    ports:
      - "3000:3000"
    container_name: citycounter-backend
    depends_on:
      - backend
